---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/7/4 9:14
---

print("sss")
fruits = { "apple", "banana" }
table.concat(fruits)

function copyfile(source, destination)
    print(destination)
    sourcefile = io.open(source, "r")
    destinationfile = io.open(destination, "w")
    destinationfile:write(sourcefile:read("*all"))
    sourcefile:close()
    destinationfile:close()
end

copyfile("D:/workspace/mengdie-zhaobiao-android/app/build/outputs/apk/official/release/zhaobiao_android_v2.3.7_61_official.apk","C:/Users/Administrator/Desktop/火标2.3.7/1.apk")

